remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: Explorador del Cosmos
description: Aplicación para explorar la biblioteca de imágenes y videos de la NASA
show_downloads: false
